### PR TITLE
Task 4 mobile ui

### PR DESCRIPTION
**Pull request by calebwoods**
Refactored UI to work on mobile more effectively and added swiping for mobile navigation.

Example below:
swipe_example

### CODE REVIEW

**Comment by danahartweg** [comment]
Wanted to let you know this hasn't been forgotten / overlooked, just don't have the time to review it now after having to take care of that other merge =(

**Comment by calebwoods** [comment]
@danahartweg no problem, it will probably look quite a bit different after I incorporate the changes from #4 and #5.

**Comment by calebwoods** [comment]
Updated example of UI

ephesians_swipe

Each verse has an indicator of which "state" is enabled, which can be activated by clicking or swipes.

**Comment by calebwoods** [comment]
Demo of the Desktop UI

ephesians_desktop

**Comment by danahartweg** [comment]
Since this has sort of fundamentally changed in the meeting this afternoon, I'm going to hold off on the review.

If you'd like it reviewed anyway, just let me know.

**Comment by calebwoods** [comment]
ephesians_swipe

@danahartweg refactored to be more in line with the direction we are going with the project.  There will definitely be a number of changes, but this gives a step in the right direction.

**Comment by danahartweg** [comment]
All righty. I'll review this evening and merge if I don't see any issues.

I started refactoring off master this afternoon to essentially remove the verse component and manage the rendering quite differently (based on a range of verse indices off the master list) across the new modes (verse, segment, chapter). Finishing those and bringing them in would be easier if this were merged.

**Comment by calebwoods** [comment]
@danahartweg Sounds good.  Merge away if it looks good to you.

**Pull request merged**
